{{- if .Values.privadoAwsSecrets.useECR }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.privadoAwsSecrets.secretName }}
  labels:
    {{- with .Values.privadoAwsSecrets.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.privadoAwsSecrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ required ".Values.privadoAwsSecrets.secretAccessKeyId is required" .Values.privadoAwsSecrets.secretAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required ".Values.privadoAwsSecrets.secretAccessKey is required" .Values.privadoAwsSecrets.secretAccessKey | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.privadoHFSecrets.name }}
  labels:
    {{- with .Values.privadoAwsSecrets.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.privadoHFSecrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  HF_ACCESS_TOKEN: {{ required ".Values.privadoHFSecrets.HF_ACCESS_TOKEN is required" .Values.privadoHFSecrets.HF_ACCESS_TOKEN | b64enc | quote }}
