apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.privadoAwsSecrets.secretName }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    {{- with .Values.privadoAwsSecrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.privadoAwsSecrets.secretAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.privadoAwsSecrets.secretAccessKey | b64enc | quote }}
