apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.bishamonten.serviceName }}
  labels: 
    {{- range $key, $val := .Values.bishamonten.serviceLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  annotations: 
    {{- range $key, $val := .Values.bishamonten.serviceAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  type: {{ .Values.bishamonten.serviceType }}
  selector:
    app: {{ .Values.bishamonten.podAppLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.bishamonten.servicePort }}
      targetPort: {{ .Values.bishamonten.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bishamonten.deploymentName }}
  labels: 
    app: bishamonten
    {{- range $key, $val := .Values.bishamonten.deploymentLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  annotations: 
    {{- range $key, $val := .Values.bishamonten.deploymentAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  # deployment to pod mapping
  replicas: {{ .Values.bishamonten.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.bishamonten.podAppLabel }}
  # pod template
  template: 
    metadata:
      labels:
        app: {{ .Values.bishamonten.podAppLabel }}
      annotations:
        checksum/hostconfig: {{ include (print $.Template.BasePath "/config.bishamonten-hostconfig.yaml") . | sha256sum | quote }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.base.imagePullSecret }}
      restartPolicy: {{ .Values.base.podRestartPolicy }}
      {{- if .Values.node.affinity.enable }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.node.affinity.key }}
                    operator: {{ .Values.node.affinity.operator }}
      {{- end }}
      {{- if .Values.node.toleration.enable }}
      tolerations:
      - key: {{ .Values.node.toleration.key }}
        operator: {{ .Values.node.toleration.operator }}
        effect: {{ .Values.node.toleration.effect }}
      {{- end }}
      containers:        
      - name: bishamonten
        image: {{ tpl .Values.bishamonten.image.name . }}:{{ .Values.bishamonten.image.tag }}
        imagePullPolicy: {{ .Values.base.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.bishamonten.containerPort }}
        {{- if or .Values.bishamonten.resources.requests.cpu .Values.bishamonten.resources.requests.memory .Values.bishamonten.resources.limits.cpu .Values.bishamonten.resources.limits.memory }}
        resources:
          {{- if or .Values.bishamonten.resources.requests.cpu .Values.bishamonten.resources.requests.memory }}
          requests: 
            {{- if .Values.bishamonten.resources.requests.cpu }}
            cpu: {{ .Values.bishamonten.resources.requests.cpu | quote }}
            {{- end }}
            {{- if .Values.bishamonten.resources.requests.memory }}
            memory: {{ .Values.bishamonten.resources.requests.memory | quote }}
            {{- end }}
          {{- end}}
          {{- if or .Values.bishamonten.resources.limits.cpu .Values.bishamonten.resources.limits.memory }}
          limits: 
            {{- if .Values.bishamonten.resources.limits.cpu }}
            cpu: {{ .Values.bishamonten.resources.limits.cpu | quote }}
            {{- end }}
            {{- if .Values.bishamonten.resources.limits.memory }}
            memory: {{ .Values.bishamonten.resources.limits.memory | quote }}
            {{- end }}
          {{- end}}
        {{- end}}
        volumeMounts:
        - name: hostconfig
          mountPath: {{ tpl .Values.bishamonten.volumeHostConfig.mountPath . }}
          subPath: {{ .Values.bishamonten.volumeHostConfig.subPath }}
      volumes:
      - name: hostconfig
        configMap:
          name: {{ .Values.bishamonten.volumeHostConfig.configName }}
