apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.bishamonten.volumeHostConfig.configName }}
data:
  env.js: |
    window.configuration = {
      host: {{ tpl .Values.bishamonten.config.hostConfig.host . | quote }},
      accountHost: {{ tpl .Values.bishamonten.config.hostConfig.accountHost . | quote }},
      isPremiseVersion: {{ .Values.bishamonten.config.hostConfig.isPremiseVersion }},
      production: {{ if .Values.base.isProduction }} 1 {{ else }} 0 {{ end }}
    }
