apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.bishamonten.volumeHostConfig.configName }}
  {{- if .Values.customLabels }}
  labels:
{{- if .Values.customLabels }}
{{ toYaml .Values.customLabels | nindent 4}}
{{- end }}
  {{- end }}
  {{- if .Values.customAnnotations }}
  annotations:
{{- if .Values.customAnnotations }}
{{ toYaml .Values.customAnnotations | nindent 4}}
{{- end }}
  {{- end }}
data:
  env.js: |
    window.configuration = {
      host: {{ tpl .Values.bishamonten.config.hostConfig.host . | quote }},
      accountHost: {{ tpl .Values.bishamonten.config.hostConfig.accountHost . | quote }},
      isPremiseVersion: {{ .Values.bishamonten.config.hostConfig.isPremiseVersion }},
      production: {{ if .Values.base.isProduction }} 1 {{ else }} 0 {{ end }}
    }
