{{- if or .Values.registry.enable .Values.autoupdates.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.secrets.name }}
  labels:
    {{- range $key, $val := .Values.registry.secrets.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  annotations:
    "helm.sh/hook-weight": "-10"
    {{- range $key, $val := .Values.registry.helmHookAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- range $key, $val := .Values.registry.secrets.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
type: Opaque
data:
  {{- if .Values.registry.secrets.AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY_ID: {{ required ".Values.registry.secrets.AWS_ACCESS_KEY_ID is required" .Values.registry.secrets.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required ".Values.registry.secrets.AWS_SECRET_ACCESS_KEY is required" .Values.registry.secrets.AWS_SECRET_ACCESS_KEY | b64enc }}
  {{- end }}
  {{- if .Values.registry.dockerhub.enable }}
  DOCKERHUB_USERNAME: {{ required ".Values.registry.dockerhub.username is required" .Values.registry.dockerhub.username | b64enc }}
  DOCKERHUB_PASSWORD: {{ required ".Values.registry.dockerhub.password is required" .Values.registry.dockerhub.password | b64enc }}
  {{- end }}

{{- end }}
