apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.secrets.name }}
  {{- if .Values.customLabels }}
  labels:
{{- if .Values.customLabels }}
{{ toYaml .Values.customLabels | nindent 4}}
{{- end }}
  {{- end }}
  {{- if .Values.customAnnotations }}
  annotations:
{{- if .Values.customAnnotations }}
{{ toYaml .Values.customAnnotations | nindent 4}}
{{- end }}
  {{- end }}
type: Opaque
data:
  # b64 encode with "echo -n secret | base64"
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.secrets.MONGO_INITDB_ROOT_USERNAME | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.secrets.MONGO_INITDB_ROOT_PASSWORD | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.encryptionSecret.name }}
  {{- if .Values.customLabels }}
  labels:
{{- if .Values.customLabels }}
{{ toYaml .Values.customLabels | nindent 4}}
{{- end }}
  {{- end }}
  {{- if .Values.customAnnotations }}
  annotations:
{{- if .Values.customAnnotations }}
{{ toYaml .Values.customAnnotations | nindent 4}}
{{- end }}
  {{- end }}
type: Opaque
data:
  MONGO_ENCRYPTION_KEY: {{ .Values.mongo.encryptionSecret.MONGO_ENCRYPTION_KEY | b64enc }}
