{{- $data := "" }}
{{- $data = printf "%s%s=%s\n" $data "_SERVER_NAME_" (.Values.base.host | quote) }}
{{- $data = printf "%s%s=%s\n" $data "CONFIG_UI_HOST" (tpl "{{ .Values.base.protocol }}://{{ .Values.base.host }}/" . | quote) }}
{{- $data = printf "%s%s=%s\n" $data "CONFIG_BACKEND_HOST" (tpl "{{ .Values.base.protocol }}://{{ .Values.base.host }}/" . | quote) }}
{{- $data = printf "%s%s=%s\n" $data "CONFIG_PARTY_SCANNER_IMAGE_URI" (tpl "{{ tpl .Values.websitescan.image.name . }}:{{ .Values.websitescan.image.tag }}" . | quote) }}
{{- range $key, $value := .Values.andromeda.enterpriseConf.values }}
{{- $data = printf "%s%s=%s\n" $data $key ($value | quote) }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: andromeda-enterprise-conf
  labels: 
    {{- range $key, $val := .Values.andromeda.enterpriseConf.secretLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  annotations: 
    {{- range $key, $val := .Values.andromeda.enterpriseConf.secretAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
type: Opaque
data:
  enterprise.conf: {{ $data | b64enc }}
