apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.secrets.name }}
  labels: 
    {{- range $key, $val := .Values.mongo.secrets.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  annotations: 
    {{- range $key, $val := .Values.mongo.secrets.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
type: Opaque
data:
  # b64 encode with "echo -n secret | base64"
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.secrets.MONGO_INITDB_ROOT_USERNAME | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.secrets.MONGO_INITDB_ROOT_PASSWORD | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.encryptionSecret.name }}
  labels: 
    {{- range $key, $val := .Values.mongo.encryptionSecret.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  annotations: 
    {{- range $key, $val := .Values.mongo.encryptionSecret.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
type: Opaque
data:
  MONGO_ENCRYPTION_KEY: {{ .Values.mongo.encryptionSecret.MONGO_ENCRYPTION_KEY | b64enc }}
